Repository DiODeProject/MuMoT, pull requests merged in 2018-12, with the labels that each got.

#233 Add getters for mathematical expressions
  mumot/__init__.py
Labels: enhancement

#234 Multicontroller fixes
  TestNotebooks/MiscTests/MuMoTtest_MultiController.ipynb
  TestNotebooks/MuMoTtest.ipynb
  docs/MuMoTuserManual.ipynb
  mumot/__init__.py
Labels: bug

#237 Fix param subscript bug
  mumot/__init__.py
Labels: bug

#242 Switch refs to ReadTheDocs docs site to GH Pages docs site
  README.md
  TestNotebooks/MiscTests/MuMoTuserManual_for_LabPresentation.ipynb
  docs/MuMoTuserManual.ipynb
  docs/source/development.rst
  mumot/__init__.py
Labels: documentation

#246 Attempt to improve code coverage
  TestNotebooks/MiscTests/MuMoTtest_GreekLetters.ipynb
  TestNotebooks/MiscTests/MuMoTtest_MasterEq.ipynb
  TestNotebooks/MiscTests/MuMoTtest_MultiController.ipynb
  TestNotebooks/MiscTests/MuMoTtest_NoiseFixedPoints.ipynb
  TestNotebooks/MiscTests/MuMoTtest_bifurcation.ipynb
  TestNotebooks/MiscTests/MuMoTtest_oneDimensionalModels.ipynb
  docs/MuMoTuserManual.ipynb
  tox.ini
Labels: testing
