Repository DiODeProject/MuMoT, pull requests merged in 2019-03, with the labels that each got.

#295 Revert to using ReadTheDocs (RTD) for building and publishing Sphinx docs
  .travis.yml
  README.md
  docs/MuMoTuserManual.ipynb
  docs/source/development.rst
  mumot/__init__.py
Labels: documentation

#299 README: use semantic line endings
  README.md
  tox.ini
Labels: testing

#303 Implemented the download button
  mumot/__init__.py
Labels: enhancement
